<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>AETP.Modules.Opportunity.Domain</AssemblyName>
    <RootNamespace>AETP.Modules.Opportunity.Domain</RootNamespace>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\AETP.BuildingBlocks.Domain\AETP.BuildingBlocks.Domain.csproj" />
  </ItemGroup>
</Project>
