// <auto-generated />
using System;
using AETP.Modules.Capability.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AETP.Modules.Capability.Infrastructure.Migrations
{
    [DbContext(typeof(CapabilityDbContext))]
    partial class CapabilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("capability")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AETP.Modules.Capability.Domain.BusinessCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiAgentPotential")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutomationPotentialPercent")
                        .HasColumnType("int");

                    b.Property<string>("BusinessContribution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessDomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DigitalizationLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpectedImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainOpportunities")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MainProblems")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MaturityLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observations")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PerformanceLevel")
                        .HasColumnType("int");

                    b.Property<string>("RelatedStrategicObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleArea")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Borrador");

                    b.Property<string>("StrategicPriority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAutonomyLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("L0");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId", "Name")
                        .IsUnique();

                    b.ToTable("BusinessCapabilities", "capability");
                });

            modelBuilder.Entity("AETP.Modules.Capability.Domain.CapabilityKpi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessCapabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Target")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessCapabilityId");

                    b.ToTable("CapabilityKpis", "capability");
                });

            modelBuilder.Entity("AETP.Modules.Capability.Domain.CapabilityKpi", b =>
                {
                    b.HasOne("AETP.Modules.Capability.Domain.BusinessCapability", null)
                        .WithMany("Kpis")
                        .HasForeignKey("BusinessCapabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AETP.Modules.Capability.Domain.BusinessCapability", b =>
                {
                    b.Navigation("Kpis");
                });
#pragma warning restore 612, 618
        }
    }
}
