<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>AETP.Modules.TransformationProgram.Application</AssemblyName>
    <RootNamespace>AETP.Modules.TransformationProgram.Application</RootNamespace>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AETP.Modules.TransformationProgram.Domain\AETP.Modules.TransformationProgram.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\AETP.BuildingBlocks.Application\AETP.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
