<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>AETP.Modules.Process.Api</AssemblyName>
    <RootNamespace>AETP.Modules.Process.Api</RootNamespace>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AETP.Modules.Process.Application\AETP.Modules.Process.Application.csproj" />
  </ItemGroup>
</Project>
