<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>AETP.Api</AssemblyName>
    <RootNamespace>AETP.Api</RootNamespace>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
    <UserSecretsId>039f485b-8247-4964-8d3f-2490fd64a5a8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="2.20.0" />
    <PackageReference Include="MediatR" Version="12.4.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../BuildingBlocks/AETP.BuildingBlocks.Domain/AETP.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="../../BuildingBlocks/AETP.BuildingBlocks.Application/AETP.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="../../BuildingBlocks/AETP.BuildingBlocks.Infrastructure/AETP.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="../../BuildingBlocks/AETP.BuildingBlocks.EventBus/AETP.BuildingBlocks.EventBus.csproj" />
    
    <!-- Modules -->
    <ProjectReference Include="../../Modules/ClientEngagement/AETP.Modules.ClientEngagement.Infrastructure/AETP.Modules.ClientEngagement.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/ClientEngagement/AETP.Modules.ClientEngagement.Api/AETP.Modules.ClientEngagement.Api.csproj" />
    <ProjectReference Include="../../Modules/Strategy/AETP.Modules.Strategy.Infrastructure/AETP.Modules.Strategy.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Strategy/AETP.Modules.Strategy.Api/AETP.Modules.Strategy.Api.csproj" />
    <ProjectReference Include="../../Modules/Capability/AETP.Modules.Capability.Infrastructure/AETP.Modules.Capability.Infrastructure.csproj" />
  </ItemGroup>
</Project>
