<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>AETP.Modules.Strategy.Api</AssemblyName>
    <RootNamespace>AETP.Modules.Strategy.Api</RootNamespace>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AETP.Modules.Strategy.Infrastructure\AETP.Modules.Strategy.Infrastructure.csproj" />
    <ProjectReference Include="..\AETP.Modules.Strategy.Application\AETP.Modules.Strategy.Application.csproj" />
  </ItemGroup>
</Project>
